// flow-typed signature: 663ac69e22b1777f34dbfea32fc1c773
// flow-typed version: <<STUB>>/dynamodb-local_v^0.0.18/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dynamodb-local'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dynamodb-local' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dynamodb-local/examples/simple' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dynamodb-local/examples/simple.js' {
  declare module.exports: $Exports<'dynamodb-local/examples/simple'>;
}
declare module 'dynamodb-local/index' {
  declare module.exports: $Exports<'dynamodb-local'>;
}
declare module 'dynamodb-local/index.js' {
  declare module.exports: $Exports<'dynamodb-local'>;
}
