// flow-typed signature: af3d7e877e6f4fe1eacccacdb527ea76
// flow-typed version: <<STUB>>/html-to-draftjs_v^0.1.0-beta15/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-to-draftjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-to-draftjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-to-draftjs/dist/html-to-draftjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-to-draftjs/dist/html-to-draftjs.js' {
  declare module.exports: $Exports<'html-to-draftjs/dist/html-to-draftjs'>;
}
