// flow-typed signature: c416195eb8155f4ceb5fb3da8a72fc3e
// flow-typed version: <<STUB>>/local-dynamo_v^0.5.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'local-dynamo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'local-dynamo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'local-dynamo/benchmark/sdk_benchmark' {
  declare module.exports: any;
}

declare module 'local-dynamo/bin/launch_local_dynamo' {
  declare module.exports: any;
}

declare module 'local-dynamo/lib/launch' {
  declare module.exports: any;
}

declare module 'local-dynamo/test/launch_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'local-dynamo/benchmark/sdk_benchmark.js' {
  declare module.exports: $Exports<'local-dynamo/benchmark/sdk_benchmark'>;
}
declare module 'local-dynamo/bin/launch_local_dynamo.js' {
  declare module.exports: $Exports<'local-dynamo/bin/launch_local_dynamo'>;
}
declare module 'local-dynamo/lib/launch.js' {
  declare module.exports: $Exports<'local-dynamo/lib/launch'>;
}
declare module 'local-dynamo/test/launch_test.js' {
  declare module.exports: $Exports<'local-dynamo/test/launch_test'>;
}
