// flow-typed signature: 7f00f557f326d016c6e6002e343c984f
// flow-typed version: <<STUB>>/react-confirm-alert_v^1.0.7/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-confirm-alert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-confirm-alert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-confirm-alert/dist/react-confirm-alert.min' {
  declare module.exports: any;
}

declare module 'react-confirm-alert/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-confirm-alert/dist/react-confirm-alert.min.js' {
  declare module.exports: $Exports<'react-confirm-alert/dist/react-confirm-alert.min'>;
}
declare module 'react-confirm-alert/lib/index.js' {
  declare module.exports: $Exports<'react-confirm-alert/lib/index'>;
}
